apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xgitops.irizzant.it
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: irizzant.it/v1alpha1
    kind: XGitOps

  patchSets:
    - name: helm-provider-ref
      patches:
      - fromFieldPath: spec.providerConfigName.helm
        toFieldPath: spec.providerConfigRef.name
    - name: kubernetes-provider-ref
      patches:
      - fromFieldPath: spec.providerConfigName.kubernetes
        toFieldPath: spec.providerConfigRef.name
        
  resources:
    - name: argocd-chart
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: argocd
        spec:
          providerConfigRef:
            name: #patched
          forProvider:
            chart:
              name: argo-cd
              repository: https://argoproj.github.io/argo-helm
              version: 5.34.1
            namespace: argocd
            values:
              configs:
                cm:
                  application.resourceTrackingMethod: annotation

      patches:
      - type: PatchSet
        patchSetName: helm-provider-ref
      - type: CombineFromComposite
        policy:
          fromFieldPath: Required
        toFieldPath: metadata.name
        combine:
          variables:
            - fromFieldPath: metadata.name
          strategy: string
          string:
            fmt: "%s-argocd"

    - name: argocd-repository
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: #patched
        spec:
          providerConfigRef:
            name: #patched
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: repo
                namespace: argocd
                labels:
                  argocd.argoproj.io/secret-type: repository
              stringData:
                type: git
                url: #patched

      patches:
      - type: PatchSet
        patchSetName: kubernetes-provider-ref
      - fromFieldPath: spec.gitOpsRepo
        toFieldPath: spec.forProvider.manifest.stringData.url
      - type: CombineFromComposite
        policy:
          fromFieldPath: Required
        toFieldPath: metadata.name
        combine:
          variables:
            - fromFieldPath: metadata.name
          strategy: string
          string:
            fmt: "%s-argocd-repository"

    - name: argocd-project
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: #patched
          forProvider:
            manifest:
              apiVersion: argoproj.io/v1alpha1
              kind: AppProject
              metadata:
                name: platform
                namespace: argocd
              spec:
                description: Platform team project
                sourceRepos:
                - #patched
                destinations:
                - namespace: '*'
                  server: 'https://kubernetes.default.svc'
                clusterResourceWhitelist:
                - group: '*'
                  kind: '*'
                namespaceResourceWhitelist:
                - group: '*'
                  kind: '*'

      patches:
      - type: PatchSet
        patchSetName: kubernetes-provider-ref
      - fromFieldPath: spec.gitOpsRepo
        toFieldPath: spec.forProvider.manifest.spec.sourceRepos[0]
      - type: CombineFromComposite
        policy:
          fromFieldPath: Required
        toFieldPath: metadata.name
        combine:
          variables:
            - fromFieldPath: metadata.name
          strategy: string
          string:
            fmt: "%s-argocd-platform-project"

    - name: argocd-application-set
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: #patched
          forProvider:
            manifest:
              apiVersion: argoproj.io/v1alpha1
              kind: ApplicationSet
              metadata:
                name: cluster-addons
                namespace: argocd
              spec:
                generators:
                - git:
                    repoURL: #patched
                    revision: HEAD
                    directories:
                    - path: cluster-addons/*
                template:
                  metadata:
                    name: '{{path.basename}}'
                  spec:
                    project: platform
                    source:
                      repoURL: #patched
                      targetRevision: HEAD
                      path: '{{path}}'
                    destination:
                      server: https://kubernetes.default.svc
                      namespace: '{{path.basename}}'
                    syncPolicy:
                      automated:
                        selfHeal: true
                        prune: true
                        allowEmpty: true
                      syncOptions:
                      - PruneLast=true
                      - CreateNamespace=true
                      - ServerSideApply=true

      patches:
      - type: PatchSet
        patchSetName: kubernetes-provider-ref
      - fromFieldPath: spec.gitOpsRepo
        toFieldPath: spec.forProvider.manifest.spec.generators[0].git.repoURL
      - fromFieldPath: spec.gitOpsRepo
        toFieldPath: spec.forProvider.manifest.spec.template.spec.source.repoURL
      - type: CombineFromComposite
        policy:
          fromFieldPath: Required
        toFieldPath: metadata.name
        combine:
          variables:
            - fromFieldPath: metadata.name
          strategy: string
          string:
            fmt: "%s-argocd-platform-applicationset"