apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xgitops.irizzant.it
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: irizzant.it/v1alpha1
    kind: XGitOps

  patchSets:
    - name: helm-provider-ref
      patches:
      - fromFieldPath: spec.providerConfigName.helm
        toFieldPath: spec.providerConfigRef.name
    - name: kubernetes-provider-ref
      patches:
      - fromFieldPath: spec.providerConfigName.kubernetes
        toFieldPath: spec.providerConfigRef.name
        
  resources:
    - name: argocd-chart
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: #patched
          annotations:
            crossplane.io/external-name: argocd
        spec:
          providerConfigRef:
            name: #patched
          forProvider:
            chart:
              name: argo-cd
              repository: https://argoproj.github.io/argo-helm
              version: 5.34.6
            namespace: argocd
            values:
              configs:
                cm:
                  application.resourceTrackingMethod: annotation

      patches:
      - fromFieldPath: metadata.name
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-argocd"
      - type: PatchSet
        patchSetName: helm-provider-ref

    - name: argocd-repository
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: #patched
        spec:
          providerConfigRef:
            name: #patched
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: repo
                namespace: argocd
                labels:
                  argocd.argoproj.io/secret-type: repository
              stringData:
                type: git
                url: #patched

      patches:
      - fromFieldPath: metadata.name
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-argocd-repository"
      - type: PatchSet
        patchSetName: kubernetes-provider-ref
      - fromFieldPath: spec.gitOpsRepo
        toFieldPath: spec.forProvider.manifest.stringData.url
      
    - name: argocd-project
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: #patched
        spec:
          providerConfigRef:
            name: #patched
          references:
          - dependsOn:
              apiVersion: helm.crossplane.io/v1beta1
              kind: Release
              name: #patched
          forProvider:
            manifest:
              apiVersion: argoproj.io/v1alpha1
              kind: AppProject
              metadata:
                name: platform
                namespace: argocd
              spec:
                description: Platform team project
                sourceRepos:
                - '*'
                destinations:
                - namespace: '*'
                  server: 'https://kubernetes.default.svc'
                clusterResourceWhitelist:
                - group: '*'
                  kind: '*'
                namespaceResourceWhitelist:
                - group: '*'
                  kind: '*'

      patches:
      - fromFieldPath: metadata.name
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-argocd-platform-project"
      - type: PatchSet
        patchSetName: kubernetes-provider-ref
      - fromFieldPath: metadata.name
        toFieldPath: spec.references[0].dependsOn.name
        transforms:
          - type: string
            string:
              fmt: "%s-argocd"

    - name: argocd-platform-application
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: #patched
        spec:
          providerConfigRef:
            name: #patched
          references:
          - dependsOn:
              apiVersion: helm.crossplane.io/v1beta1
              kind: Release
              name: #patched
          forProvider:
            manifest:
              apiVersion: argoproj.io/v1alpha1
              kind: Application
              metadata:
                name: platform
                namespace: argocd
              spec:
                project: platform
                source:
                  targetRevision: HEAD
                  path: #patched
                  repoUrl: #patched
                destination:
                  server: https://kubernetes.default.svc
                  namespace: argocd
                syncPolicy:
                  automated:
                    selfHeal: true
                    prune: true
                    allowEmpty: true
      patches:
      - fromFieldPath: metadata.name
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-argocd-platform-application"
      - type: PatchSet
        patchSetName: kubernetes-provider-ref
      - fromFieldPath: metadata.name
        toFieldPath: spec.references[0].dependsOn.name
        transforms:
          - type: string
            string:
              fmt: "%s-argocd"
      - fromFieldPath: spec.gitOpsPath
        toFieldPath: spec.forProvider.manifest.spec.source.path
      - fromFieldPath: spec.gitOpsRepo
        toFieldPath: spec.forProvider.manifest.spec.source.repoURL
      