apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvclusters.irizzant.it
spec:
  group: irizzant.it
  names:
    kind: XVCluster
    plural: xvclusters
  claimNames:
    kind: VCluster
    plural: vclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: {}