apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: gitops
spec:
  package: irizzant/gitops:main
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1