name: ci
on:
  push:
  pull_request:
    types: [ labeled ]

jobs:
  docker:
    if: contains(github.event.pull_request.labels.*.name, 'CI') || github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}          
      - name: Build
        uses: crossplane-contrib/xpkg-action@v0.2.0
        env:
          OS_ARCH: linux_amd64
        with:
          channel: stable
          version: current
          command: build configuration -f crossplane/gitops --name=gitops.xpkg
      - name: Push dev branch
        if: ${{ github.ref_name != 'main' }}
        uses: crossplane-contrib/xpkg-action@v0.2.0
        with:
          command: push configuration -f crossplane/gitops/gitops.xpkg irizzant/gitops:latest
      - name: Push main branch
        if: ${{ github.ref_name == 'main' }}
        uses: crossplane-contrib/xpkg-action@v0.2.0
        with:
          command: push configuration -f crossplane/gitops/gitops.xpkg irizzant/gitops:${GITHUB_REF_NAME}
  
